# Generated by Django 2.0.1 on 2018-08-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartMonitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.IntegerField(choices=[(1, 'NikkeiMiniFuture')])),
                ('current_trend', models.IntegerField()),
                ('prev_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prev_top', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prev_bottom', models.DecimalField(decimal_places=2, max_digits=7)),
                ('has_bellow_bottom', models.BooleanField()),
                ('has_over_top', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.IntegerField(choices=[(1, 'NikkeiMiniFuture')])),
                ('date_time', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.IntegerField(choices=[(1, 'NikkeiMiniFuture')])),
                ('datetime', models.DateTimeField()),
                ('current_status', models.CharField(max_length=1)),
                ('current_position', models.CharField(max_length=10)),
                ('current_coins', models.IntegerField()),
                ('current_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('position_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prev_top', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prev_bottom', models.DecimalField(decimal_places=2, max_digits=7)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=7)),
                ('has_trade', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
